# Generated by Django 5.1.7 on 2025-03-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.SlugField()),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('scrollX', models.IntegerField(default=0)),
                ('scrollY', models.IntegerField(default=0)),
                ('timestamp', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('isClicked', models.BooleanField(default=False)),
                ('isScrolling', models.BooleanField(default=False)),
            ],
        ),
    ]
